.TH "deprecated" 3 "Sun Dec 10 2023" "Version 0.1.0" "lib<fancy_string>" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBGlobal \fBfancy_string_array_append_and_destroy\fP (fancy_string_array_t *const self, fancy_string_array_t *array)\fP" 1c
Looking back, this method should not have existed from the beginning, since it is not consistent with other methods whose names are ending with \fC_and_destroy\fP\&. 
.PP

